### ISSUE TITLE
snow bug

### ISSUE THREAD

**Issue by 00c** [HybridDog/replacer#5]
Replacer fails to replace snow, it place another snow on top of snow. Until its full then you get other
`Error: nothing is not a node`
`Placing 'moreblocks:iron_stone' failed, another node appeared: 'default:snow'`

**Comment by HybridDog** [comment]
https://github.com/HybridDog/replacer/commit/bc518158b386ef766bff48af97994a0c776fccce
Thanks for spotting this. 
I've found another problem: When placing snow onto snow using replacer, the snow node grows, no snowblock appears and the node above it gets removed. This bug belongs to snow. The node above gets removed because the replacer digs it, which looks a bit strange. (So maybe the message should be added back as warning?)
